language: node_js
node_js:
- 6.10.0
before_script:
- npm install
script: ng build
deploy:
  provider: s3
  access_key_id: AKIAIHSQYVRI2NZ7YX2A\

  secret_access_key:
    secure: lCE/+nl9ytjVt0MMcpvX2HGiaXq7aTTBF/v6HOJXg5YzzcYosd2aQuvhu8goTsjcMcCg1W3oFErpUgAsBMORvClTedzJ2lX4HXUXs7S1Ii6TEqud38jPzr9mbyu9kkwT06Wy1AJb0RpN733onTaNUut1cX8kH5YlC5uJYGjwpebRsij0G4vWjAXnhr3yLO
            Omx63xAjq2EFyQPnU0v2Lxo1aWZCU2vRoVbOAGVnS3kfIJskQmqMLmBQsZaExDe1V4st9wHmh+5Qoz9Bh2ckOu8xBthAqZk3FoE4vZ8qWetFSDwwGuX9YPSdNwGgtaKZhSA5niNrrD5GnShwXVAqn6lgD3hCS8pU/LAAu3exIBzImLpr5ilEPwHJH8IO5MNXE7dsYB+c1
            mN1P4u8sSmTcJwS2sYwaqVk7115zUSOlBtJ0NzMtKmggLvyPa4LJo8xRYwgXoi1CfnUIMA00agRAdBPzfCsrXT7OvxViMM5SV9hMFEDYd9MXufZfE875Y3RZ8RNvrHUklzxVmYCIdXCvRUgg/2tNbWD1KzqEDMRXgjeiZfuU74jbcWOtJxYizHnpS53dfgGUH5RxSm+mK
            da7vfJaupmZV7BWCNhkLsYAyZ3Xe4OWZc8R69Rin6uICiAQ7ZkKuoAhg3t0AbAfyCXCJaE0MKvIn+5IrchGA1NLYwqk=
  bucket: drivetogain.ga
  region: us-west-2
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui-angular
